name: Publish Minecraft Mods
on: [release]

jobs:
  build:
  # aaaa
    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          # You don't need this section if you don't want to publish
          # your assets to GitHub
          github-token: ${{ secrets.GITHUB_TOKEN }}
